// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Cabinet) Location(ctx context.Context) (*Location, error) {
	result, err := c.Edges.LocationOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryLocation().Only(ctx)
	}
	return result, err
}

func (c *Cabinet) Game(ctx context.Context) (*Game, error) {
	result, err := c.Edges.GameOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryGame().Only(ctx)
	}
	return result, err
}

func (l *Location) Cabinets(ctx context.Context) (result []*Cabinet, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = l.NamedCabinets(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = l.Edges.CabinetsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = l.QueryCabinets().All(ctx)
	}
	return result, err
}
