// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GalvinGao/otogenavi-backend/internal/ent/location"
	"github.com/GalvinGao/otogenavi-backend/internal/x/postgis"
)

// Location is the model entity for the Location schema.
type Location struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DeduplicationKey holds the value of the "deduplication_key" field.
	DeduplicationKey string `json:"deduplication_key,omitempty"`
	// RawAddress holds the value of the "raw_address" field.
	RawAddress string `json:"raw_address,omitempty"`
	// Coordinate holds the value of the "coordinate" field.
	Coordinate *postgis.PointS `json:"coordinate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationQuery when eager-loading is set.
	Edges        LocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LocationEdges holds the relations/edges for other nodes in the graph.
type LocationEdges struct {
	// Cabinets holds the value of the cabinets edge.
	Cabinets []*Cabinet `json:"cabinets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedCabinets map[string][]*Cabinet
}

// CabinetsOrErr returns the Cabinets value or an error if the edge
// was not loaded in eager-loading.
func (e LocationEdges) CabinetsOrErr() ([]*Cabinet, error) {
	if e.loadedTypes[0] {
		return e.Cabinets, nil
	}
	return nil, &NotLoadedError{edge: "cabinets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Location) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case location.FieldCoordinate:
			values[i] = new(postgis.PointS)
		case location.FieldID, location.FieldName, location.FieldDeduplicationKey, location.FieldRawAddress:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Location fields.
func (l *Location) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case location.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				l.ID = value.String
			}
		case location.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				l.Name = value.String
			}
		case location.FieldDeduplicationKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deduplication_key", values[i])
			} else if value.Valid {
				l.DeduplicationKey = value.String
			}
		case location.FieldRawAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_address", values[i])
			} else if value.Valid {
				l.RawAddress = value.String
			}
		case location.FieldCoordinate:
			if value, ok := values[i].(*postgis.PointS); !ok {
				return fmt.Errorf("unexpected type %T for field coordinate", values[i])
			} else if value != nil {
				l.Coordinate = value
			}
		default:
			l.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Location.
// This includes values selected through modifiers, order, etc.
func (l *Location) Value(name string) (ent.Value, error) {
	return l.selectValues.Get(name)
}

// QueryCabinets queries the "cabinets" edge of the Location entity.
func (l *Location) QueryCabinets() *CabinetQuery {
	return NewLocationClient(l.config).QueryCabinets(l)
}

// Update returns a builder for updating this Location.
// Note that you need to call Location.Unwrap() before calling this method if this Location
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Location) Update() *LocationUpdateOne {
	return NewLocationClient(l.config).UpdateOne(l)
}

// Unwrap unwraps the Location entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Location) Unwrap() *Location {
	_tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Location is not a transactional entity")
	}
	l.config.driver = _tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Location) String() string {
	var builder strings.Builder
	builder.WriteString("Location(")
	builder.WriteString(fmt.Sprintf("id=%v, ", l.ID))
	builder.WriteString("name=")
	builder.WriteString(l.Name)
	builder.WriteString(", ")
	builder.WriteString("deduplication_key=")
	builder.WriteString(l.DeduplicationKey)
	builder.WriteString(", ")
	builder.WriteString("raw_address=")
	builder.WriteString(l.RawAddress)
	builder.WriteString(", ")
	builder.WriteString("coordinate=")
	builder.WriteString(fmt.Sprintf("%v", l.Coordinate))
	builder.WriteByte(')')
	return builder.String()
}

// NamedCabinets returns the Cabinets named value or an error if the edge was not
// loaded in eager-loading with this name.
func (l *Location) NamedCabinets(name string) ([]*Cabinet, error) {
	if l.Edges.namedCabinets == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := l.Edges.namedCabinets[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (l *Location) appendNamedCabinets(name string, edges ...*Cabinet) {
	if l.Edges.namedCabinets == nil {
		l.Edges.namedCabinets = make(map[string][]*Cabinet)
	}
	if len(edges) == 0 {
		l.Edges.namedCabinets[name] = []*Cabinet{}
	} else {
		l.Edges.namedCabinets[name] = append(l.Edges.namedCabinets[name], edges...)
	}
}

// Locations is a parsable slice of Location.
type Locations []*Location
