// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cabinet is the predicate function for cabinet builders.
type Cabinet func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)
