package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/GalvinGao/otogenavi-backend/internal/ent"
	"github.com/GalvinGao/otogenavi-backend/internal/model"
)

// CoordinateWithin is the resolver for the coordinateWithin field.
func (r *locationWhereInputResolver) CoordinateWithin(ctx context.Context, obj *ent.LocationWhereInput, data *model.CoordinateWithin) error {
	return fmt.Errorf("not implemented")
}
